/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.trs.x46FW

import com.trs.x46FW.main
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        /*val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")*/
    }
}
